### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by bugproof** [bugproof/Tomlyn.Extensions.Configuration#2]
So TOML is case-sensitive but all configuration implementations ignore cases

e.g.

```toml
name = "Gina"
Name = "gina"
```

will result in "gina" overriding "Gina" because Tomlyn will treat them as separate keys but that's not the case with IConfiguration.
